<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__55r1 _1kbt</name>
   <tag></tag>
   <elementGuidId>3872a463-57c0-44fc-831a-c13019b993a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div._55r1._1kbt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginform']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4101b977-697f-4436-8af6-8aeafb5fd9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_55r1 _1kbt</value>
      <webElementGuid>45290885-c8f9-4ad9-9f9f-8f015280ee8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginform&quot;)/div[@class=&quot;clearfix _5466 _44mg&quot;]/div[1]/div[@class=&quot;_55r1 _1kbt&quot;]</value>
      <webElementGuid>5dcb5ff7-f449-4694-9d21-d3aa76f588dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginform']/div/div/div</value>
      <webElementGuid>32b72320-401f-4ab5-a832-9a2161242be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div</value>
      <webElementGuid>29991e40-d42e-41d8-90bf-3aba509dd5a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
