<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select your pronounShe Wish her a ha_90e2d2</name>
   <tag></tag>
   <elementGuidId>f5611848-c359-4d60-b72a-888b45dba60c</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;preferred_pronoun&quot;]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='preferred_pronoun']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>210e5203-0b77-4bed-a76a-b9c980729504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select your pronoun</value>
      <webElementGuid>faaabf3b-881f-4fe8-8537-f7e8d03b02a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>preferred_pronoun</value>
      <webElementGuid>b8e8c503-25d7-4057-bff5-3cad90d2f0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_7-16 _9hk6 _5dba _9m5o</value>
      <webElementGuid>e7c62894-35c6-4ef6-a844-7b205c1f163b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select your pronounShe: &quot;Wish her a happy birthday!&quot;He: &quot;Wish him a happy birthday!&quot;They: &quot;Wish them a happy birthday!&quot;</value>
      <webElementGuid>0cd5d375-8e75-480c-88f4-4fe361f11657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_3_p_gI&quot;)/select[@class=&quot;_7-16 _9hk6 _5dba _9m5o&quot;]</value>
      <webElementGuid>e9d2cfa0-d15c-45b2-b929-34dc44421782</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='preferred_pronoun']</value>
      <webElementGuid>16d9f1df-3f8c-4d1f-8851-e5306e03bc27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_3_p_gI']/select</value>
      <webElementGuid>10fb70b6-f78f-4680-9ed0-d5b38f053939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/select</value>
      <webElementGuid>ab86fd7f-e5d4-401f-a89c-29403425ea94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'preferred_pronoun']</value>
      <webElementGuid>8374c564-df22-4973-9456-0a328f011773</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
