<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_day</name>
   <tag></tag>
   <elementGuidId>a8b35101-e59d-4c2f-b181-8552e4c2e1ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='day']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6220f17d-4abc-40e5-ae62-6ff7f9222f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Day</value>
      <webElementGuid>1a6a7e4b-4bc0-4444-9e74-1aef246be682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthday_day</value>
      <webElementGuid>27602e87-ec33-4765-bea7-cef2f189299a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>8ea1ac40-bb83-4e86-bfdf-60a0b2aa912d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Day</value>
      <webElementGuid>f427e321-3bd7-418a-9f29-6fc07292ab44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9407 _5dba _9hk6 _8esg</value>
      <webElementGuid>6bcfa1f1-e6f6-424f-9480-a01c853771bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12345678910111213141516171819202122232425262728293031</value>
      <webElementGuid>dc755a2d-efd2-4073-9122-03631a150083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;day&quot;)</value>
      <webElementGuid>de591469-ed82-4e3a-9875-52352355b3aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='day']</value>
      <webElementGuid>c920e8db-23ab-4af7-ac63-440a164182b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='u_4_l_OA']/span/select</value>
      <webElementGuid>905e3635-d8b2-46d7-bb54-a7380179d992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b6c3f14d-e985-45dd-8725-221b69c1b77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'birthday_day' and @id = 'day' and @title = 'Day' and (text() = '12345678910111213141516171819202122232425262728293031' or . = '12345678910111213141516171819202122232425262728293031')]</value>
      <webElementGuid>46ccfc4d-11ee-4201-ac87-597b31d46c4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
