<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign Up</name>
   <tag></tag>
   <elementGuidId>addf4f8d-af4a-48ec-8fee-57ec99fbd26f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_3_s_Dk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='u_3_s_Dk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a120be36-377f-4f4c-9a05-2a3dca955fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3941cda4-5263-4cc9-ab26-34bf7788db81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6j mvm _6wk _6wl _58mi _3ma _6o _6v</value>
      <webElementGuid>e65bb3ea-2da9-46b1-8fe7-f69c6dcf146f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>websubmit</value>
      <webElementGuid>9a44fdbe-53c9-4a44-8d16-1b3d442d5cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_3_s_Dk</value>
      <webElementGuid>9db8215f-783c-4919-9a04-f5bf110c1745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up</value>
      <webElementGuid>33c15be2-f5ef-402b-bbcd-5a78f40f9ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_3_s_Dk&quot;)</value>
      <webElementGuid>1d01ff14-5d65-45dc-9a87-4db0134e6203</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='u_3_s_Dk']</value>
      <webElementGuid>ace9fab6-6184-42a1-8a78-04034ab006bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reg_form_box']/div[11]/button</value>
      <webElementGuid>54922258-984c-46fd-ad1a-db579d62bac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/button</value>
      <webElementGuid>91f066c9-9310-4783-b425-658b83e49c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'websubmit' and @id = 'u_3_s_Dk' and (text() = 'Sign Up' or . = 'Sign Up')]</value>
      <webElementGuid>e3413e81-2a9e-41dc-9b72-9c2dbc37734f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
