<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_sex</name>
   <tag></tag>
   <elementGuidId>58ec6db2-52ba-4f49-b7dd-857f24b3579d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_3_5_kF</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='u_3_5_kF']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b5d690d-3117-444c-8a45-e6cce74ace0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4b40a84d-a60a-48d3-803d-04e457b0ca5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_8esa</value>
      <webElementGuid>69231601-a29d-44b3-82f3-38611ca5343f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sex</value>
      <webElementGuid>2d9aa240-4e83-4d93-9efd-ecabb7df2cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>48f821e7-42ae-4180-b616-d4af7128a7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_3_5_kF</value>
      <webElementGuid>90f88cc6-5d73-4edf-bd34-c9db3e44e110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_3_5_kF&quot;)</value>
      <webElementGuid>555a8381-29f9-4354-98cb-52b9ca78ed96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='u_3_5_kF']</value>
      <webElementGuid>d5e4708f-5279-46d7-ab0e-b193011f80f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='u_3_o_/1']/span[2]/input</value>
      <webElementGuid>d5d20d7d-09ba-4f34-b7c3-9b59c8268f8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>09d991e3-704d-4c1c-b6f6-bd5378c8f6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'sex' and @id = 'u_3_5_kF']</value>
      <webElementGuid>cf7acdab-e087-4293-91c9-63b7befe1136</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
